"""
pipeline/citation_validator.py
================================
Post-generation URL allowlist validator.

After the synthesis model produces sources[], this module strips any URL
that is not on the approved domain allowlist and logs a warning.  This
ensures the API response never accidentally cites unofficial or hallucinated
sources.

Approved domains:
    Employment law:
        legislation.govt.nz      — Acts and regulations
        employment.govt.nz       — Employment NZ guidance
        era.govt.nz              — Employment Relations Authority decisions
        courtsofnz.govt.nz       — Employment Court decisions
        nzlii.org                — NZ Legal Information Institute (case law)
        business.govt.nz         — Employer guidance (MBIE)
        mbie.govt.nz             — Ministry of Business, Innovation and Employment

    Tax law (added 2026-05-04):
        ird.govt.nz              — IRD official guidance
        taxtechnical.ird.govt.nz — Tax Information Bulletins, public rulings, SPSs
        taxpolicy.ird.govt.nz    — IRD tax policy
        legislation.govt.nz      — (already covered above)

Public API:
    validate(sources: list[dict]) -> ValidationResult

    ValidationResult:
        .valid_sources    list[dict]   — sources whose URLs passed allowlist check
        .stripped_sources list[dict]   — sources that were removed
        .all_valid        bool         — True if nothing was stripped
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from urllib.parse import urlparse

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Allowlist — domains whose content we trust as authoritative NZ sources
# ---------------------------------------------------------------------------

ALLOWED_DOMAINS: set[str] = {
    # Employment law
    "legislation.govt.nz",
    "www.legislation.govt.nz",
    "employment.govt.nz",
    "www.employment.govt.nz",
    "era.govt.nz",
    "www.era.govt.nz",
    "courtsofnz.govt.nz",
    "www.courtsofnz.govt.nz",
    "nzlii.org",
    "www.nzlii.org",
    "business.govt.nz",
    "www.business.govt.nz",
    "mbie.govt.nz",
    "www.mbie.govt.nz",
    # Tax law
    "ird.govt.nz",
    "www.ird.govt.nz",
    "taxtechnical.ird.govt.nz",
    "www.taxtechnical.ird.govt.nz",
    "taxpolicy.ird.govt.nz",
    "www.taxpolicy.ird.govt.nz",
    # Tenancy law
    "tenancy.govt.nz",
    "www.tenancy.govt.nz",
    "communitylaw.org.nz",
    "www.communitylaw.org.nz",
    "cab.org.nz",
    "www.cab.org.nz",
    "hud.govt.nz",
    "www.hud.govt.nz",
    "govt.nz",
    "www.govt.nz",
    "forms.justice.govt.nz",
    "www.forms.justice.govt.nz",
    # Stats (labour market tool)
    "stats.govt.nz",
    "www.stats.govt.nz",
}

# Pseudo-sources that are always valid (generated by the labour stats tool)
_STATS_SOURCE_PATTERN = re.compile(
    r"mbie\.govt\.nz|stats\.govt\.nz|labour.market", re.IGNORECASE
)


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class ValidationResult:
    valid_sources: list[dict] = field(default_factory=list)
    stripped_sources: list[dict] = field(default_factory=list)

    @property
    def all_valid(self) -> bool:
        return len(self.stripped_sources) == 0


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def is_allowed(url: str) -> bool:
    """
    Return True if the URL's domain is on the allowlist.

    Args:
        url: Full URL string (e.g. "https://www.ird.govt.nz/gst")

    Returns:
        True if domain is in ALLOWED_DOMAINS or matches STATS_SOURCE_PATTERN.
    """
    if not url or url in ("Unknown", "N/A", ""):
        return False

    # Stats pseudo-URLs always pass
    if _STATS_SOURCE_PATTERN.search(url):
        return True

    try:
        parsed = urlparse(url)
        domain = parsed.netloc.lower()
        return domain in ALLOWED_DOMAINS
    except Exception:
        return False


def validate(sources: list[dict]) -> ValidationResult:
    """
    Validate a list of source dicts against the allowlist.

    Each source dict should have a "url" key.  Sources with missing or
    unknown URLs are stripped.

    Args:
        sources: List of source dicts from AgentResponse.sources

    Returns:
        ValidationResult with valid_sources and stripped_sources separated.
    """
    result = ValidationResult()

    for source in sources:
        url = source.get("url", "")
        if is_allowed(url):
            result.valid_sources.append(source)
        else:
            log.warning(
                "[citation_validator] Stripped non-allowlisted source: %s (url=%s)",
                source.get("title", "?"),
                url,
            )
            result.stripped_sources.append(source)

    if result.stripped_sources:
        log.warning(
            "[citation_validator] %d/%d sources stripped (not on allowlist)",
            len(result.stripped_sources),
            len(sources),
        )

    return result
