"""
DB abstraction layer for the Text-to-SQL pipeline.

Provides a single, uniform interface (`DBEngine`) that the rest of the
pipeline (schema context builder, SQL generator, query router) can use
without caring whether the underlying store is DuckDB, Snowflake, or
Databricks.

Default backend
---------------
DuckDB, reading from ``data/stats_nz.db`` (produced by
``pipeline.text_to_sql.load_data``). This is the only backend that is
fully wired up today.

Future backends
---------------
``SnowflakeEngine`` and ``DatabricksEngine`` are included as stubs so
the downstream pipeline can be written against the abstract interface.
Swapping in a real cloud warehouse should only require filling in the
stubbed methods — no changes to the SQL generator or router.

Usage
-----
    from pipeline.db_engine import get_engine

    db = get_engine()                    # defaults to DuckDB
    tables = db.list_tables()
    schema = db.get_schema("labour_force_status")
    df     = db.query("SELECT * FROM labour_force_status LIMIT 5")
    db.close()

    # or as a context manager:
    with get_engine() as db:
        df = db.query("SELECT COUNT(*) AS n FROM labour_force_status")

Safety
------
``query()`` is read-only. Statements that look like DDL/DML
(INSERT/UPDATE/DELETE/DROP/ALTER/CREATE/TRUNCATE/MERGE/REPLACE) are
rejected before hitting the backend. This is a defence-in-depth check
meant for LLM-generated SQL — it is NOT a substitute for using a
read-only database role in production.
"""
from __future__ import annotations

import re
from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd

# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DUCKDB_PATH = PROJECT_ROOT / "data" / "stats_nz.db"

# -----------------------------------------------------------------------------
# Read-only guard
# -----------------------------------------------------------------------------
# Statements that should never be generated by the Text-to-SQL layer.
# Kept deliberately strict — the LLM should only ever produce SELECT / WITH.
_FORBIDDEN_KEYWORDS = (
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE",
    "TRUNCATE", "MERGE", "REPLACE", "GRANT", "REVOKE", "ATTACH",
    "DETACH", "COPY", "EXPORT", "IMPORT", "PRAGMA", "SET",
)


def _strip_sql_comments(sql: str) -> str:
    """Remove -- line comments and /* block */ comments from SQL."""
    # block comments (non-greedy, multiline)
    sql = re.sub(r"/\*.*?\*/", " ", sql, flags=re.DOTALL)
    # line comments
    sql = re.sub(r"--[^\n]*", " ", sql)
    return sql


def _assert_read_only(sql: str) -> None:
    """Raise ValueError if `sql` contains any write/DDL keyword.

    The check is conservative on purpose: the caller is an LLM, not a
    trusted human. Using a read-only database role in addition to this
    is strongly recommended for production.
    """
    cleaned = _strip_sql_comments(sql).upper()
    # Tokenise on word boundaries to avoid false positives like "INSERTED_AT".
    tokens = set(re.findall(r"\b[A-Z_]+\b", cleaned))
    hits = sorted(tokens & set(_FORBIDDEN_KEYWORDS))
    if hits:
        raise ValueError(
            f"Refusing to execute non-read-only SQL. "
            f"Forbidden keyword(s) found: {', '.join(hits)}"
        )
    # Must contain at least one SELECT (or WITH ... SELECT).
    if "SELECT" not in tokens:
        raise ValueError("SQL must contain a SELECT statement.")


# -----------------------------------------------------------------------------
# Schema metadata types
# -----------------------------------------------------------------------------
@dataclass
class ColumnInfo:
    """Minimal column description used by downstream prompt builders."""
    name: str
    dtype: str
    nullable: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return {"name": self.name, "dtype": self.dtype, "nullable": self.nullable}


@dataclass
class TableSchema:
    """Schema of a single table, normalised across backends."""
    name: str
    columns: List[ColumnInfo]
    row_count: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "columns": [c.to_dict() for c in self.columns],
            "row_count": self.row_count,
        }


# -----------------------------------------------------------------------------
# Abstract base class
# -----------------------------------------------------------------------------
class DBEngine(ABC):
    """Uniform interface for every supported SQL backend.

    Implementations must be safe to construct cheaply and must release
    their connection on ``close()`` / context-manager exit.
    """

    backend: str = "abstract"

    # -- lifecycle -----------------------------------------------------------
    @abstractmethod
    def close(self) -> None:
        """Release the underlying connection."""

    def __enter__(self) -> "DBEngine":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        self.close()

    # -- introspection -------------------------------------------------------
    @abstractmethod
    def list_tables(self) -> List[str]:
        """Return the user-facing table names available to the Text-to-SQL layer."""

    @abstractmethod
    def get_schema(self, table: str) -> TableSchema:
        """Return column names, types, and row count for a single table."""

    def get_all_schemas(self) -> List[TableSchema]:
        """Return schemas for every table — default implementation uses ``list_tables``."""
        return [self.get_schema(t) for t in self.list_tables()]

    # -- querying ------------------------------------------------------------
    @abstractmethod
    def query(self, sql: str) -> pd.DataFrame:
        """Execute a read-only SQL statement and return the result as a DataFrame."""


# -----------------------------------------------------------------------------
# DuckDB implementation (default)
# -----------------------------------------------------------------------------
class DuckDBEngine(DBEngine):
    """DuckDB-backed engine reading from a local ``.db`` file.

    This is the default backend for local development and for the
    current hosted version of the Intelligence Hub.
    """

    backend = "duckdb"

    def __init__(self, db_path: Optional[Path] = None, read_only: bool = True):
        import duckdb  # local import so the stubs don't force the dep at import time

        self.db_path = Path(db_path) if db_path else DEFAULT_DUCKDB_PATH
        if not self.db_path.exists():
            raise FileNotFoundError(
                f"DuckDB file not found at {self.db_path}. "
                f"Run `python -m pipeline.text_to_sql.load_data` first."
            )
        # read_only=True gives us an extra belt-and-braces guarantee on top
        # of _assert_read_only(). DuckDB will raise if any write is attempted.
        self._conn = duckdb.connect(str(self.db_path), read_only=read_only)

    # -- lifecycle -----------------------------------------------------------
    def close(self) -> None:
        try:
            self._conn.close()
        except Exception:
            pass

    # -- introspection -------------------------------------------------------
    def list_tables(self) -> List[str]:
        rows = self._conn.execute(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema = 'main' ORDER BY table_name"
        ).fetchall()
        return [r[0] for r in rows]

    def get_schema(self, table: str) -> TableSchema:
        # Columns
        col_rows = self._conn.execute(
            "SELECT column_name, data_type, is_nullable "
            "FROM information_schema.columns "
            "WHERE table_schema = 'main' AND table_name = ? "
            "ORDER BY ordinal_position",
            [table],
        ).fetchall()
        if not col_rows:
            raise KeyError(f"Table not found: {table}")

        columns = [
            ColumnInfo(name=name, dtype=dtype, nullable=(nullable == "YES"))
            for name, dtype, nullable in col_rows
        ]

        # Row count — cheap on DuckDB even without indexes.
        row_count = self._conn.execute(
            f'SELECT COUNT(*) FROM "{table}"'
        ).fetchone()[0]

        return TableSchema(name=table, columns=columns, row_count=row_count)

    # -- querying ------------------------------------------------------------
    def query(self, sql: str) -> pd.DataFrame:
        _assert_read_only(sql)
        return self._conn.execute(sql).fetch_df()


# -----------------------------------------------------------------------------
# Snowflake stub
# -----------------------------------------------------------------------------
class SnowflakeEngine(DBEngine):
    """Stub Snowflake engine — interface only, not yet implemented.

    Intended shape once wired up: uses ``snowflake-connector-python`` with
    a service account that has read-only access to a single schema, and
    translates ``TableSchema`` via ``INFORMATION_SCHEMA.COLUMNS``.
    """

    backend = "snowflake"

    def __init__(self, **kwargs):
        raise NotImplementedError(
            "SnowflakeEngine is not implemented yet. "
            "Use get_engine('duckdb') for now."
        )

    def close(self) -> None:  # pragma: no cover
        raise NotImplementedError

    def list_tables(self) -> List[str]:  # pragma: no cover
        raise NotImplementedError

    def get_schema(self, table: str) -> TableSchema:  # pragma: no cover
        raise NotImplementedError

    def query(self, sql: str) -> pd.DataFrame:  # pragma: no cover
        raise NotImplementedError


# -----------------------------------------------------------------------------
# Databricks stub
# -----------------------------------------------------------------------------
class DatabricksEngine(DBEngine):
    """Stub Databricks engine — interface only, not yet implemented.

    Intended shape once wired up: uses ``databricks-sql-connector`` against
    a SQL Warehouse, with Unity Catalog ``INFORMATION_SCHEMA`` providing
    the schema introspection.
    """

    backend = "databricks"

    def __init__(self, **kwargs):
        raise NotImplementedError(
            "DatabricksEngine is not implemented yet. "
            "Use get_engine('duckdb') for now."
        )

    def close(self) -> None:  # pragma: no cover
        raise NotImplementedError

    def list_tables(self) -> List[str]:  # pragma: no cover
        raise NotImplementedError

    def get_schema(self, table: str) -> TableSchema:  # pragma: no cover
        raise NotImplementedError

    def query(self, sql: str) -> pd.DataFrame:  # pragma: no cover
        raise NotImplementedError


# -----------------------------------------------------------------------------
# Factory
# -----------------------------------------------------------------------------
_BACKENDS = {
    "duckdb": DuckDBEngine,
    "snowflake": SnowflakeEngine,
    "databricks": DatabricksEngine,
}


def get_engine(backend: str = "duckdb", **kwargs) -> DBEngine:
    """Return a configured ``DBEngine`` for the requested backend.

    Parameters
    ----------
    backend:
        One of ``"duckdb"`` (default), ``"snowflake"``, ``"databricks"``.
    **kwargs:
        Passed through to the engine constructor. For DuckDB, the most
        useful is ``db_path``.

    Examples
    --------
    >>> db = get_engine()                                # default DuckDB
    >>> db = get_engine("duckdb", db_path="/tmp/x.db")   # custom path
    """
    backend = backend.lower()
    if backend not in _BACKENDS:
        raise ValueError(
            f"Unknown backend: {backend!r}. "
            f"Supported: {sorted(_BACKENDS)}"
        )
    return _BACKENDS[backend](**kwargs)


# -----------------------------------------------------------------------------
# Smoke test
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    # Quick sanity check: list tables, show schema of the first, run a
    # trivial query. Run from project root:
    #     python -m pipeline.db_engine
    with get_engine() as db:
        tables = db.list_tables()
        print(f"Backend: {db.backend}")
        print(f"Tables ({len(tables)}):")
        for t in tables:
            print(f"  - {t}")

        if tables:
            first = tables[0]
            schema = db.get_schema(first)
            print(f"\nSchema for '{first}' ({schema.row_count:,} rows):")
            for col in schema.columns:
                print(f"  {col.name:<20} {col.dtype}")

            print(f"\nSample rows from '{first}':")
            df = db.query(f'SELECT * FROM "{first}" LIMIT 3')
            print(df.to_string(index=False))
