"""
pipeline/output_guard.py
=========================
Post-generation output guard middleware.

Sits between the synthesis model and the user. Inspects every generated
answer and rejects + regenerates non-compliant answers up to MAX_REGEN
times before falling back to a safe REFUSE_WITH_REFERRAL response.

Checks (in order):
  1. Banned-phrase scan (English + Chinese)
  2. Required section headings (per routing_outcome template)
  3. Risk footer verbatim presence
  4. Second-person framing catch-all

Public API:
    output_guard(
        answer_text,
        routing_outcome,
        domain_label,
        domain_tier,
        generate_fn,          # Callable[[str], str]  violation_note → new answer
        max_regenerations=2,
    ) -> GuardResult

    build_footer(domain_label, domain_tier) -> str
    RISK_FOOTER_VERBATIM    str constant
    TEMPLATE_HEADINGS       dict constant
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import Callable

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Standard risk footer (verbatim — used both in check and in fallback)
# ---------------------------------------------------------------------------

RISK_FOOTER_VERBATIM = (
    "General information only — not legal advice.\n"
    "This response was generated by an AI assistant from public sources and may\n"
    "contain errors or be out of date. The law and individual circumstances vary;\n"
    "nothing here is a substitute for advice from a lawyer or the relevant\n"
    "statutory body. For urgent or high-stakes matters, please contact a\n"
    "professional.\n\n"
    "Free help: Community Law (https://communitylaw.org.nz) · Citizens Advice\n"
    "Bureau 0800 367 222"
)

# ---------------------------------------------------------------------------
# Escalated footers for H2/H3 domains (appended after standard footer)
# ---------------------------------------------------------------------------

_ESCALATED_FOOTER: dict[str, str] = {
    "family": (
        "This topic is one where professional advice is particularly important.\n"
        "For family law matters, please contact Family Legal Aid or Community Law "
        "(communitylaw.org.nz) before acting on any information here."
    ),
    "criminal": (
        "This topic is one where professional advice is particularly important.\n"
        "For criminal matters, please contact the Police Detention Legal Assistance "
        "scheme or Legal Aid (legalaid.govt.nz) before acting on any information here."
    ),
    "wills_estates": (
        "This topic is one where professional advice is particularly important.\n"
        "For wills and estate matters, please contact a lawyer or Public Trust "
        "(publictrust.co.nz) before acting on any information here."
    ),
    "tax": (
        "This topic is one where professional advice is particularly important.\n"
        "For tax matters, please contact IRD (ird.govt.nz) or a chartered accountant "
        "before acting on any information here."
    ),
}


def build_footer(domain_label: str, domain_tier: str) -> str:
    """Return the full risk footer for this domain, including escalated text if applicable."""
    footer = RISK_FOOTER_VERBATIM
    if domain_tier in ("H2", "H3") and domain_label in _ESCALATED_FOOTER:
        footer += "\n\n" + _ESCALATED_FOOTER[domain_label]
    return footer


# ---------------------------------------------------------------------------
# Required section headings per routing template
# ---------------------------------------------------------------------------

TEMPLATE_HEADINGS: dict[str, list[str]] = {
    "DIRECT_ANSWER": [],    # No mandatory headings beyond risk footer
    "STRUCTURED_INFORMATIONAL": [
        "General information about",
        "Where to get",
    ],
    "STRUCTURED_ADVICE_SKELETON": [
        "General information about",
        "Here is what the law says",
        "Factors that typically matter",
        "Options people in this situation",
        "Time limits and deadlines",
        "Why this is general information",
        "Where to get advice",
    ],
    "REFUSE_WITH_REFERRAL": [],   # Free-form; just risk footer required
}

# ---------------------------------------------------------------------------
# Banned phrases — compiled once at module load
# ---------------------------------------------------------------------------

_BANNED_EN: list[tuple[re.Pattern, str]] = [
    (re.compile(r"\byou\s+should\b", re.I),
     "you_should"),
    (re.compile(r"\bthe\s+best\s+thing\s+to\s+do\b", re.I),
     "best_thing_to_do"),
    (re.compile(r"\bin\s+your\s+(case|situation|circumstances)\b", re.I),
     "in_your_case"),
    (re.compile(r"\bthis\s+is\s+(a\s+)?personal\s+grievance\b", re.I),
     "characterise_pg"),
    (re.compile(r"\bthis\s+is\s+unfair\s+dismissal\b", re.I),
     "characterise_ud"),
    (re.compile(r"\bthis\s+is\s+a\s+breach\s+of\s+contract\b", re.I),
     "characterise_breach"),
    (re.compile(r"\byou\s+are\s+entitled\s+to\b", re.I),
     "entitled_to"),
    (re.compile(r"\byou\s+have\s+a\s+(strong|weak|good|poor)\s+case\b", re.I),
     "merits_opinion"),
    (re.compile(r"\bI\s+(recommend|suggest|would\s+advise|'d\s+advise)\b", re.I),
     "direct_advice"),
    (re.compile(r"\b(definitely|certainly|guaranteed|without\s+a\s+doubt)\b", re.I),
     "false_precision"),
    (re.compile(r"\bas\s+your\s+lawyer\b", re.I),
     "holding_out"),
    # Categorical legal conclusion without a nearby citation marker
    (re.compile(r"\bthis\s+is\s+(illegal|legal)\b(?![^.]{0,60}\[)", re.I),
     "uncited_legal_conclusion"),
]

_BANNED_ZH: list[tuple[re.Pattern, str]] = [
    (re.compile(r"你应该"),       "zh_you_should"),
    (re.compile(r"你需要"),       "zh_you_need"),
    (re.compile(r"你必须"),       "zh_you_must"),
    (re.compile(r"最好的办法是"), "zh_best_thing"),
    (re.compile(r"在你的情况下"), "zh_in_your_case"),
    (re.compile(r"你这种情况"),   "zh_your_situation"),
    (re.compile(r"这属于"),       "zh_characterise"),
    (re.compile(r"这就是"),       "zh_this_is"),
    (re.compile(r"你有权"),       "zh_entitled"),
    (re.compile(r"我建议"),       "zh_i_recommend"),
    (re.compile(r"我推荐"),       "zh_i_suggest"),
    (re.compile(r"一定|肯定|必然"), "zh_false_precision"),
]

BANNED_PATTERNS: list[tuple[re.Pattern, str]] = _BANNED_EN + _BANNED_ZH

# Second-person framing catch-all (catches creative paraphrases)
_SECOND_PERSON_RE = re.compile(
    r"\b(your\s+(case|situation|matter|circumstances)|"
    r"in\s+your\s+(specific\s+)?(case|situation|circumstances))\b",
    re.I,
)

# ---------------------------------------------------------------------------
# Fallback refusal text (used when max regenerations are exhausted)
# ---------------------------------------------------------------------------

_FALLBACK_TEMPLATE = (
    "I wasn't able to produce a response that meets our quality standards for this question. "
    "This sometimes happens with complex or sensitive topics.\n\n"
    "For accurate, tailored information please contact:\n"
    "  • Community Law (communitylaw.org.nz) — free legal information\n"
    "  • Citizens Advice Bureau — 0800 367 222\n"
    "  • The relevant government agency for your area (IRD, Employment NZ, Tenancy Services)\n\n"
    "---\n"
    + RISK_FOOTER_VERBATIM
)

# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class GuardResult:
    ok: bool
    text: str
    regeneration_count: int = 0
    banned_phrase_hits: list[str] = field(default_factory=list)
    fell_back: bool = False
    violations: list[tuple[str, str | None]] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _check(
    answer_text: str,
    routing_outcome: str,
    domain_label: str,
    domain_tier: str,
) -> tuple[list[tuple[str, str | None]], list[str]]:
    """
    Run all checks. Return (violations, banned_hits).

    violations: list of (check_name, detail_or_None)
    banned_hits: list of banned-phrase label strings that matched
    """
    violations: list[tuple[str, str | None]] = []
    banned_hits: list[str] = []

    # (1) Banned phrases
    for pattern, label in BANNED_PATTERNS:
        if pattern.search(answer_text):
            violations.append(("banned_phrase", label))
            banned_hits.append(label)

    # (2) Required section headings
    for heading in TEMPLATE_HEADINGS.get(routing_outcome, []):
        if heading.lower() not in answer_text.lower():
            violations.append(("missing_section", heading))

    # (3) Risk footer verbatim (check for the key identifier line)
    if "General information only — not legal advice." not in answer_text:
        violations.append(("missing_risk_footer", None))

    # (4) Second-person framing catch-all
    m = _SECOND_PERSON_RE.search(answer_text)
    if m:
        violations.append(("second_person_framing", m.group(0)))

    return violations, banned_hits


def _build_regen_instruction(violations: list[tuple[str, str | None]]) -> str:
    """Build a clear violation note to prepend to the regeneration request."""
    lines = ["Your previous answer violated the following rules. Rewrite it fixing EVERY violation:"]
    for check_name, detail in violations:
        if check_name == "banned_phrase":
            lines.append(f"  - BANNED PHRASE used: '{detail}' — replace with hedged third-person language.")
        elif check_name == "missing_section":
            lines.append(f"  - MISSING SECTION: '{detail}' — you must include this section heading.")
        elif check_name == "missing_risk_footer":
            lines.append(
                "  - RISK FOOTER MISSING — end your answer with this text verbatim:\n"
                "    'General information only — not legal advice. ...'"
            )
        elif check_name == "second_person_framing":
            lines.append(
                f"  - SECOND-PERSON FRAMING: '{detail}' — use third-person: "
                "'a person in this position', 'an employee in this scenario', etc."
            )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def output_guard(
    answer_text: str,
    routing_outcome: str,
    domain_label: str,
    domain_tier: str,
    generate_fn: Callable[[str], str],
    max_regenerations: int = 2,
    *,
    _regen_count: int = 0,
    _cumulative_hits: list[str] | None = None,
) -> GuardResult:
    """
    Inspect answer_text and regenerate if violations are found.

    Args:
        answer_text:       The model-generated answer to inspect.
        routing_outcome:   One of DIRECT_ANSWER / STRUCTURED_INFORMATIONAL /
                           STRUCTURED_ADVICE_SKELETON / REFUSE_WITH_REFERRAL.
        domain_label:      e.g. "employment", "tax" — drives escalated footer.
        domain_tier:       e.g. "H2", "M" — drives escalated footer.
        generate_fn:       Callable that takes a violation_note string and
                           returns a new answer string. Typically a closure
                           over the Anthropic client and synthesis prompt.
        max_regenerations: How many times to retry before falling back.

    Returns:
        GuardResult with the final (clean or fallback) text and metadata.
    """
    if _cumulative_hits is None:
        _cumulative_hits = []

    violations, banned_hits = _check(answer_text, routing_outcome, domain_label, domain_tier)
    _cumulative_hits.extend(banned_hits)

    if not violations:
        # Clean — ensure the full footer (including escalated) is appended
        footer = build_footer(domain_label, domain_tier)
        if footer not in answer_text:
            answer_text = answer_text.rstrip() + "\n\n---\n" + footer
        log.info(
            "[output_guard] Clean. regen_count=%d banned_hits=%s",
            _regen_count,
            _cumulative_hits,
        )
        return GuardResult(
            ok=True,
            text=answer_text,
            regeneration_count=_regen_count,
            banned_phrase_hits=_cumulative_hits,
            fell_back=False,
            violations=[],
        )

    log.warning(
        "[output_guard] Violations found (attempt %d/%d): %s",
        _regen_count + 1,
        max_regenerations + 1,
        violations,
    )

    if max_regenerations > 0:
        regen_note = _build_regen_instruction(violations)
        try:
            new_answer = generate_fn(regen_note)
        except Exception as exc:
            log.exception("[output_guard] generate_fn raised: %s", exc)
            # treat as exhausted
            return GuardResult(
                ok=True,
                text=_FALLBACK_TEMPLATE,
                regeneration_count=_regen_count + 1,
                banned_phrase_hits=_cumulative_hits,
                fell_back=True,
                violations=violations,
            )
        return output_guard(
            new_answer,
            routing_outcome,
            domain_label,
            domain_tier,
            generate_fn,
            max_regenerations - 1,
            _regen_count=_regen_count + 1,
            _cumulative_hits=_cumulative_hits,
        )

    # Max regenerations exhausted — return safe fallback
    log.error(
        "[output_guard] Fallback triggered after %d regenerations. violations=%s",
        _regen_count,
        violations,
    )
    return GuardResult(
        ok=True,
        text=_FALLBACK_TEMPLATE,
        regeneration_count=_regen_count,
        banned_phrase_hits=_cumulative_hits,
        fell_back=True,
        violations=violations,
    )
